# Same as `code-quality-pr.yaml` but triggered on commit to main branch
# and runs on all files (instead of only the changed ones)

name: precommit-checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "release/*"]

permissions: read-all

jobs:
  code-quality:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: |
          . $HOME/.cargo/bin/uv sync
          echo PATH="$PWD/.venv/bin:$PATH" >> $GITHUB_ENV

      - name: Pre-commit on changed files
        uses: pre-commit/action@v3.0.1
